name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: Run Unit Tests and Generate Coverage Report
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history is required for SonarQube analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install pytest pytest-cov

      - name: Run pytest with coverage
        run: |
          # Measure coverage for code in the src folder
          pytest --cov=src --cov-report=lcov -v  # Run tests and generate coverage report in LCOV format
          # Debug: ensure coverage file exists
          cat coverage.lcov

  sonarqube:
    name: SonarQube Scan
    runs-on: windows-latest
    needs: build-and-test  # This ensures SonarQube scan runs only after the tests are successful

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          extra-properties: |
            sonar.projectKey=JOSHUACRAZES_SSDLS  # Your project key
            sonar.organization=joshuacrazes  # Your organization (for SonarCloud)
            sonar.sources=src  # Point to src folder where your source code resides
            sonar.python.coverage.reportPaths=coverage.lcov  # Path to the coverage report
            sonar.coverage.exclusions=**/*test*.py  # Exclude test files from coverage calculation
            sonar.cpd.exclusions=**/*test*.py  # Exclude test files from code duplication analysis
