name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    name: Unit Tests + SonarQube + Docker
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history is required for SonarQube analysis

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies and run unit tests with coverage
      - name: Install dependencies and Run Unit Tests with Coverage
        run: |
          pip install flask pytest pytest-cov
          python -m pytest src/test_app.py --cov=src --cov-report=xml -v  # Run tests and generate coverage report in XML

      # Step 4: SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml  # Path to coverage report generated in Step 3
            -Dsonar.sources=src  # Analyze files in the 'src' directory

     
